main_menu_line1   !scr "    keano game corp proudly presnets    "
main_menu_title   !scr "                 storko                 " 

main_menu_top  	!scr "     ]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]     "
				!scr "                                        "
				!scr "              start new game            "
				!scr "              help                      "
main_menu_btm	!scr "                                        "
			    !scr "                                        "
				!scr "                                        "
				!scr "     ]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]     "
