main_menu_top  	!scr "     ]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]     "
				!scr "     ]]                          ]]     "
				!scr "     ]]                          ]]     "
				!scr "   ]]   select difficulty level:   ]]   "
				!scr " ]]                                  ]] "
main_menu_btm	!scr " ]]             * easy               ]] "
			    !scr "   ]]             hard             ]]   "
				!scr "     ]]                          ]]     "
				!scr "     ]]                          ]]     "
				!scr "     ]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]     "
